apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    snapshot.gingersociety.org/enabled: "true"
    volume.kubernetes.io/selected-node: "artifactory-control-plane"
  name: verdaccio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: node-registry-service-api-secrets
type: Opaque
stringData:
  ROCKET_SECRET_KEY: {{shared.ROCKET_SECRET_KEY}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verdaccio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verdaccio
  template:
    metadata:
      labels:
        app: verdaccio
    spec:
      containers:
        - name: verdaccio
          image: docker.gingersociety.org/ginger-society/node-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: hampi-redis-auth
                  key: url
            - name: PACKAGES_DIR
              value: "/verdaccio/storage"
            - name: PUBLIC_BASE_URL
              value: "https://npm.gingersociety.org"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: verdaccio-secrets   # secret name
                  key: JWT_SECRET_KEY       # key inside the secret
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: chikkamagaluru-rabbitmq-auth
                  key: amqp_url
            - name: SYNC_PACKAGES
              value: "@gingersociety/ginger-ui"
            - name: IAM_LOGIN_URL
              value: "https://iam.{{HOSTING_FQDN}}/#node-packages-registry/login"   # ← replace with your IAM URL
            - name: RUST_LOG
              value: "debug"
            - name: ROCKET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: node-registry-service-api-secrets
                  key: ROCKET_SECRET_KEY
            - name: ROCKET_ADDRESS
              value: "0.0.0.0"

            - name: ROCKET_PORT
              value: "8080"

          volumeMounts:
            - name: storage
              mountPath: /verdaccio/storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: verdaccio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: verdaccio-service
spec:
  selector:
    app: verdaccio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
