apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-db-runtime
  labels:
    app: iam-db-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam-db-runtime
  template:
    metadata:
      labels:
        app: iam-db-runtime
    spec:
      imagePullSecrets:
        - name: regcred

      initContainers:
        - name: wait-for-db
          image: postgres:latest
          command:
            - sh
            - -c
            - |
              until pg_isready -h iam-postgresql -p 5432 -U postgres; do 
                echo "Waiting for DB..."
                sleep 5
              done

      containers:
        - name: iam-db-runtime
          image: docker.gingersociety.org/ginger-society/iam-db-runtime:main
          command: ["/bin/sh", "-c", "/app/migrate.sh && /app/run.sh"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          env:
            - name: HOST
              value: "iam-db.gingersociety.org"

            - name: APP_ID
              value: "iam-db-runtime"

            - name: DB_NAME
              value: "iam-db"

            - name: DB_USERNAME
              value: "postgres"

            - name: DB_HOST
              value: "iam-postgresql"

            - name: DB_PORT
              value: "5432"

            # ✅ Pull password from Helm-created secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iam-postgresql
                  key: postgres-password
        