apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-multi-arch-rust-image-pipeline
  annotations:
    x-gitter-trigger-branch: '["refs/heads/main", "refs/heads/dev-*"]'
    x-gitter-enabled: "true"
spec:
  params:
    - name: image_tag
      type: string
    - name: org_id
      type: string

  tasks:
    - name: macos-builds
      runAfter:
        - init-credentials
      taskRef:
        apiVersion: gingersociety.org/v1alpha1
        kind: RemoteTask
        name: macos-builds
      params:
        - name: namespace
          value: default
        - name: env          
          value: |
            - name: GIT_REPO_NAME
              value: "$(params.repo)"
            - name: IMAGE_TAG
              value: "$(params.image_tag)"
            - name: BINARIES_TO_BUILD
              value: "$(params.binaries_to_build)"
            - name: BINARIES_TO_UPLOAD
              value: "$(params.binaries_to_upload)"

    - name: notify-version-update
      runAfter:
        - macos-builds
      taskSpec:
        steps:
          - name: echo
            image: alpine
            script: |
              #!/bin/sh
              echo "Hello World - multi-arch-rust image build is done!"