apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-tekton-task-images-pipeline
  annotations:
    x-gitter-trigger-branch: '["refs/heads/main", "refs/heads/dev-*"]'
    x-gitter-enabled: "true"
spec:
  params:
    - name: image_tag
      type: string
    - name: org_id
      type: string
  tasks:
    - name: build-push-ginger-auth
      runAfter:
        - clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: build-and-push-dockerfile-image
          - name: namespace
            value: default
      params:
        - name: image_repo
          value: "tekton-task-ginger-auth"
        - name: image_tag
          value: "latest"
        - name: dockerfile_path
          value: "jobs/ginger-auth.Dockerfile"
        - name: build_context
          value: "jobs"
        - name: org_id
          value: "$(params.org_id)"

    - name: build-push-ginger-infra
      runAfter:
        - clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: build-and-push-dockerfile-image
          - name: namespace
            value: default
      params:
        - name: image_repo
          value: "tekton-task-ginger-infra"
        - name: image_tag
          value: "latest"
        - name: dockerfile_path
          value: "jobs/ginger-infra.Dockerfile"
        - name: build_context
          value: "jobs"
        - name: org_id
          value: "$(params.org_id)"

    - name: build-push-ginger-connector-and-db
      runAfter:
        - clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: build-and-push-dockerfile-image
          - name: namespace
            value: default
      params:
        - name: image_repo
          value: "tekton-task-ginger-connector-and-db"
        - name: image_tag
          value: "latest"
        - name: dockerfile_path
          value: "jobs/ginger-connector-and-db.Dockerfile"
        - name: build_context
          value: "jobs"
        - name: org_id
          value: "$(params.org_id)"

    - name: build-push-buildah
      runAfter:
        - clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: build-and-push-dockerfile-image
          - name: namespace
            value: default
      params:
        - name: image_repo
          value: "tekton-task-buildah"
        - name: image_tag
          value: "latest"
        - name: dockerfile_path
          value: "jobs/enhanced-buildah.Dockerfile"
        - name: build_context
          value: "jobs"
        - name: org_id
          value: "$(params.org_id)"

    - name: build-push-gitter
      runAfter:
        - clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: build-and-push-dockerfile-image
          - name: namespace
            value: default
      params:
        - name: image_repo
          value: "tekton-task-gitter"
        - name: image_tag
          value: "latest"
        - name: dockerfile_path
          value: "jobs/gitter.Dockerfile"
        - name: build_context
          value: "jobs"
        - name: org_id
          value: "$(params.org_id)"

    - name: build-push-k8-controller-and-runner-base
      runAfter:
        - clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: build-and-push-dockerfile-image
          - name: namespace
            value: default
      params:
        - name: image_repo
          value: "k8-controller-and-runner-base"
        - name: image_tag
          value: "latest"
        - name: dockerfile_path
          value: "jobs/k8-controller-and-runner.Dockerfile"
        - name: build_context
          value: "jobs"
        - name: org_id
          value: "$(params.org_id)"

    - name: build-push-python3
      runAfter:
        - clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: build-and-push-dockerfile-image
          - name: namespace
            value: default
      params:
        - name: image_repo
          value: "python3"
        - name: image_tag
          value: "latest"
        - name: dockerfile_path
          value: "jobs/python3.Dockerfile"
        - name: build_context
          value: "jobs"
        - name: org_id
          value: "$(params.org_id)"

    - name: build-push-py-lib-base
      runAfter:
        - build-push-python3
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: build-and-push-dockerfile-image
          - name: namespace
            value: default
      params:
        - name: image_repo
          value: "py-lib-base"
        - name: image_tag
          value: "latest"
        - name: dockerfile_path
          value: "jobs/py-lib-base.Dockerfile"
        - name: build_context
          value: "jobs"
        - name: org_id
          value: "$(params.org_id)"

    - name: notify-version-update
      runAfter:
        - build-push-ginger-auth
        - build-push-ginger-infra
        - build-push-ginger-connector-and-db
        - build-push-buildah
        - build-push-gitter
        - build-push-k8-controller-and-runner-base
        - build-push-py-lib-base
      taskSpec:
        steps:
          - name: echo
            image: alpine
            script: |
              #!/bin/sh
              echo "Hello World - all tekton-task image builds are done!"