# redis.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-api-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-api-staging
  template:
    metadata:
      labels:
        app: redis-api-staging
    spec:
      containers:
      - name: redis-api-staging
        image: redis:6.2
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-staging
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-api-staging
